# This config file for Travis CI utilizes https://github.com/coincar-sim/mrt_cmake_modules_ci/ package.
# THIS FILE IS BEING USED TO CI-TEST THE CI SCRIPT ITSELF - do not use this for your repo but instead use the version in README.md
sudo: required
dist: trusty
services:
  - docker
language: generic
compiler:
  - gcc

env:
  global:
    - ROS_DISTRO=kinetic
    - DEPENDENCIES_ROSINSTALL=travis.rosinstall

before_script:
  - ln -s . .mrt_cmake_modules_ci # pretend to have the usual location

script:
  - .mrt_cmake_modules_ci/travis.sh
